[fetch_depth_layer][OpenCV] operator= compile error
Update depth_layer no match for ‘operator=’ error

There was an issue with how the cv::Ptr was being set.

This is fixed by setting the normals_estimator_ pointer similarly to how the plane_estimator_ pointer is being set.

The error below would occur:
fetch_robot_ws/src/fetch_ros/fetch_depth_layer/src/depth_layer.cpp:239:28:
error: no match for ‘operator=’ (operand types are ‘cv::Ptr<cv::rgbd::RgbdNormals>’ and ‘cv::rgbd::RgbdNormals*’)
       normals_estimator_ = new RgbdNormals(cv_ptr->image.rows,cv_ptr->image.cols,  cv_ptr->image.depth(),K_);
                            ^~~~